---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: ubuntu:xenial
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ANSIBLE0013
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
